included:
  - Package.swift
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm

allow_zero_lintable_files: false
reporter: xcode

disabled_rules:
  - trailing_comma
  - nesting

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - modifier_order
  - redundant_nil_coalescing
  - toggle_bool

analyzer_rules:
  - unused_import

identifier_name:
  min_length:
    error: 3
  max_length: 60
  excluded:
    - id

large_tuple:
  error: 3

cyclomatic_complexity:
  error: 15

function_body_length:
  error: 120

file_length:
  error: 500

type_body_length:
  error: 400
